CREATE DATABASE mssql1;
GO
USE mssql1;
GO
CREATE LOGIN admin WITH PASSWORD = 'wp03cYFsCKC5', CHECK_POLICY = ON;
GO
CREATE USER admin FOR LOGIN admin;
GO
ALTER ROLE db_owner ADD MEMBER [admin];
GO